name: Test
on:
  pull_request:
  push:
    branches:
      - main

    paths-ignore:
      - "**.md"

jobs:
  test:
    runs-on: ubuntu-latest
    name: Setup MoonBit
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Moonbit
        uses: hustcer/setup-moonbit@develop

      - name: Check Moonbit Version
        run: |
          moon version --all
          moon update
          moon install

      - name: Run tests with coverage
        run: |
          moon test --enable-coverage

      - name: Generate and upload coverage report
        run: |
          moon coverage report \
            -f coveralls \
            -o codecov_report.json \
            --service-name github \
            --service-job-id "$GITHUB_RUN_ID" \
            --service-pull-request "${{ github.event.pull_request.number }}" \
            --send-to codecov
        env:
          CODECOV_TOKEN: d6e0e4fb-91ef-4e53-9b63-a1c1ad1c03fb
